wlx-redis:
  image: redis:latest
  ports:
  - "6379:6379"

wlx-mysql:
  image: mysql:latest
  ports:
  - "3306:3306"
  environment:
  - MYSQL_DATABASE=wlx
  - MYSQL_USER=root
  - MYSQL_ROOT_PASSWORD=123456
  volumes:
  - ./docker/mysql:/var/mysql

#wlx:
#  build: .
#  volumes:
#    - .:/go
#  ports:
#    - "8080:8080"
#  links:
#    - wlx-mysql
#    - wlx-redis
